# Generated by Django 4.2.13 on 2024-06-03 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_tag_diary_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tags',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
