# Generated by Django 4.2.13 on 2024-06-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_diary_tags_diary_user_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(),
        ),
    ]
